# Generated by Django 4.2 on 2025-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=256)),
                ('trip_description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('customers', models.ManyToManyField(to='webapp.customer')),
                ('guides', models.ManyToManyField(to='webapp.guide')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='guided_trips',
            field=models.ManyToManyField(to='webapp.trip'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_trips',
            field=models.ManyToManyField(to='webapp.trip'),
        ),
    ]
