# Generated by Django 4.2 on 2025-05-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='guides',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_trips',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.trip'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guided_trips',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.trip'),
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('trip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.trip')),
                ('customers', models.ManyToManyField(blank=True, null=True, to='webapp.customer')),
                ('guides', models.ManyToManyField(blank=True, null=True, to='webapp.guide')),
            ],
            bases=('webapp.trip',),
        ),
    ]
