# Generated by Django 4.2 on 2025-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_trip_customers_remove_trip_guides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_trips',
            field=models.ManyToManyField(blank=True, to='webapp.trip'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guided_trips',
            field=models.ManyToManyField(blank=True, to='webapp.trip'),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='customers',
            field=models.ManyToManyField(blank=True, to='webapp.customer'),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='guides',
            field=models.ManyToManyField(blank=True, to='webapp.guide'),
        ),
    ]
