# Generated by Django 4.2 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_trip_image_alter_customer_customer_trips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
