# Generated by Django 4.2 on 2025-05-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_trip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdmin',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.customer')),
                ('trips', models.ManyToManyField(blank=True, to='webapp.trip')),
            ],
            bases=('webapp.customer',),
        ),
    ]
