# Generated by Django 4.2 on 2025-05-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_customeradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
