# Generated by Django 4.2 on 2025-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_trip_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
