# Generated by Django 4.2 on 2025-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_trip_trip_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
