# Generated by Django 4.2 on 2025-05-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_customer_customer_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_trips',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_trip', to='webapp.trip'),
        ),
    ]
