# Generated by Django 4.2 on 2025-05-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_customer_customer_trips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
