# Generated by Django 4.2 on 2025-05-29 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_customer_customer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
