# Generated by Django 4.2 on 2025-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_tripdetail_customers_remove_tripdetail_guides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(default='-', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_last_name',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
