# Generated by Django 4.2 on 2025-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_customer_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
