# Generated by Django 4.2 on 2025-06-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_freeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_images', to='webapp.trip'),
        ),
    ]
